spring.application.name=NotificationSystem
server.port=9099

#Key for JWT
jwt.secret=${JWT_SECRET}

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging (Optional: to debug SQL statements and Hibernate behavior)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
rate.limit.protected.apis=/admin


#Mail Related Properties
# SMTP Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${TEST_EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Show detailed health 
management.endpoint.health.show-details=always






